controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

default-route:
    path: /{req}
    defaults: { _controller: 'App\Controller\DefaultController::catchAll' }
    requirements:
        req: ".*"